// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "Frog1":return img`
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
.................cccc..............
..........cccc..cddddc.............
.........cccccc.ddd11dcc...........
........cdc1ddccdcc11dc7c..........
........c4cc44cc4ccc44ccc..........
........cc444ccc444444ccc..........
.........cccccccc4444ccccc.........
......ccccccccccccccccccccccc......
.....ccccccdddd111dccccccc77cc.....
....cccccc44444444444ccccc77cc.....
....ccccc4e444444444e4cccccccc.....
....cccccee444444444eeccccccc......
.....ccccee444444444eecccccc.......
.......cceee4444444eeeccccc........
........cceeeeeeeeeeeccccc.........
.....ccccccceeeeeeeeecccccc........
....ccccccccccccccccccc7cc7c.......
....cccccccccccccccccccccccc.......
.....cccccccccccccccccccccc........
...................................
...................................
...................................
...................................
...................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
